/* Generated by Together */

package com.dimata.common.entity.system;

/* import java */
import java.util.*;

/* import java */
import com.dimata.common.entity.system.*;

public class AppValue {
    
    public static final String SESS_APP_VALUE = "SESS_APP_VALUE";

    static Hashtable properties = new Hashtable();
    
    public static Hashtable getSystemProperties(){
        return properties;
    }

    public static void loadSystemProperty(){
        
        System.out.println(" ");
        System.out.println(" ");
        System.out.println("======-------------=====================");
        System.out.println("======-------------=====================");
        System.out.println("---LOADING SYSTEM PROPERTY INTO JSP SESSION");
        System.out.println(" ");
        System.out.println(" ");
        
        properties = new Hashtable();
        Vector listAll = PstSystemProperty.list(0,0, "", "");
        if(listAll!=null && listAll.size()>0){
            for(int i=0; i<listAll.size(); i++){
                SystemProperty sysprop = (SystemProperty)listAll.get(i);
                properties.put(""+sysprop.getName(), ""+sysprop.getValue());
            }
        }
        
    }
    
    
    public static String getValueByKey(String keys){
        
        String value = "";
        try{
            value = (String)properties.get(keys);
            System.out.println("--- GETTING PROPERTY VALUE : "+keys+", result : "+value);
        }
        catch(Exception e){
            value = "";            
        }
        
        if(value==null){
            value = "";
        }
        
        return value;
    }

}
