/* Generated by Together */

package com.dimata.pos.entity.masterCashier;

import com.dimata.qdep.entity.Entity;

public class CashMaster extends Entity{
    
    private long locationId;
    private int cashierNumber;
    private double cashTax = 0;
    private double cashService = 0;      
    private String priceType = "";          

    public long getLocationId(){
        return locationId;
    }
    public void setLocationId(long locationId){
        this.locationId=locationId;
    }

    /** Getter for property cashierNumber.
     * @return Value of property cashierNumber.
     *
     */
    public int getCashierNumber() {
        return this.cashierNumber;
    }
    
    /** Setter for property cashierNumber.
     * @param cashierNumber New value of property cashierNumber.
     *
     */
    public void setCashierNumber(int cashierNumber) {
        this.cashierNumber = cashierNumber;
    }
    
    public double getCashTax(){
        return cashTax;
    }
    public void setCashTax(double cashTax){
        this.cashTax=cashTax;
    }

    public double getCashService(){
        return cashService;
    }
    public void setCashService(double cashService){
        this.cashService=cashService;
    }

    public String getPriceType(){
        return priceType;
    }
    public void setPriceType(String priceType){
        this.priceType=priceType;
    }    
}
