/* Generated by Together */

package com.dimata.qdep.form;

// import java

// import dimata
import com.dimata.util.*;
import java.util.Vector;

public class Control {

     private int start = 0;

     public int actionList(int listCmd, int start, int vectSize, int recordToGet) {
     
     switch(listCmd){                
         case Command.FIRST :                
             this.start = 0;
             break;

         case Command.PREV :                
             this.start = start - recordToGet;
             if(this.start < 0){
                 this.start = 0;
             }                
             break;

         case Command.NEXT :
             this.start = start + recordToGet;
             if(this.start >= vectSize){
                 this.start = this.start - recordToGet;
             }                
             break;
             
         case Command.LAST :
             int mdl = vectSize % recordToGet;
             if(mdl>0){
                 this.start = vectSize - mdl;
             }
             else{
                 this.start = vectSize - recordToGet;
             }                
             
             break;
             
         default:
             this.start = start;
             if(vectSize<1)
                 this.start = 0;                
             
             if(start > vectSize){
                 mdl = vectSize % recordToGet;
                 if(mdl>0){
                     this.start = vectSize - mdl;
                 }
                 else{
                     this.start = vectSize - recordToGet;
                 }                
             }                
             break;
     }
     return this.start;
 }
     
     public int actList(int iVecSize, int iMaxRecordToList){
         int maxIndex =  0;
        if((iVecSize) % iMaxRecordToList == 0){
            maxIndex = (iVecSize) / iMaxRecordToList;
        }else{
            maxIndex = (iVecSize - 1) / iMaxRecordToList;
        }
         
        for(int i = 0; i < maxIndex; i++){ 
             if(i != 0){
                        start = (iMaxRecordToList * i) + 1;    
                   }else{
                        start = (iMaxRecordToList * i);
                   } 
             System.out.println("start index ke : "+i+" = "+start);
        }
        return this.start;
     }
     
     public static void main(String arg[]){
        Control objControl = new Control(); 
        int start = objControl.actList(1435,15);
       
     }
}
