/* Generated by Together */

package com.dimata.pos.entity.balance;

import com.dimata.qdep.entity.Entity;
import java.util.Date;

public class CashCashier extends Entity {
    private long cashMasterId;
    private java.util.Date openDate;
    private long appUserId;
    private long svpOid;
    private String svpName="";
    private long svpCloseOid=0;
    private String svpCloseName="";
    //variable shift
    private long shiftId;

    public CashCashier(){
    }

   public long getCashMasterId(){
        return cashMasterId;
    }

    public void setCashMasterId(long cashMasterId){
        this.cashMasterId=cashMasterId;
    }

    public Date getCashDate(){
        return openDate;
    }
    public void setCashDate(Date openDate){
        this.openDate=openDate;
    }


    public long getAppUserId(){
        return appUserId;
    }

    public void setAppUserId(long appUserId){
        this.appUserId=appUserId;
    }

   
    public long getSpvOid(){
        return svpOid;
    }
    public void setSpvOid(long svpOid){
        this.svpOid=svpOid;
    }

    public String getSpvName(){
        return svpName;}
    public void setSpvName(String svpName){
        this.svpName=svpName;}

      public long getSpvCloseOid(){
        return svpCloseOid;
    }

    public void setSpvCloseOid(long svpCloseOid){
        this.svpCloseOid=svpCloseOid;
    }

    public String getSpvCloseName(){
        return svpCloseName;}
    public void setSpvCloseName(String svpCloseName){
        this.svpCloseName=svpCloseName;}

    /**
     * @return the shiftId
     */
    public long getShiftId() {
        return shiftId;
    }

    /**
     * @param shiftId the shiftId to set
     */
    public void setShiftId(long shiftId) {
        this.shiftId = shiftId;
    }


}
