/* Generated by Together */

package com.dimata.gui.jsp;

import com.dimata.aiso.entity.periode.ActivityPeriod;
import com.dimata.aiso.entity.periode.PstActivityPeriod;
import com.dimata.util.Formater;
import java.util.*;

public class ControlCheckBox {
    public int getWidth() { return width; }
    
    public void setWidth(int width) {
        int x = 0;
        try {
            x = Integer.parseInt(tableWidth) / width;
        }
        catch (Exception e) {
            try {
                int lengthTemp = tableWidth.length();
                String tmp = tableWidth.substring(0, lengthTemp - 1);
                //System.out.println(tmp);
                x = Integer.parseInt(tmp) / width;
            }
            catch (Exception exc) {
                System.out.println("Hey.. we got an exception  =" + exc.toString());
            }
        }
        this.cellWidth = String.valueOf(x) + "%";
        this.width = width;
    }
    
    public int getHeight() { return height; }
    
    public void setHeight(int height) { this.height = height; }
    
    public String getCellSpace() { return cellSpace; }
    
    public void setCellSpace(String cellSpace) { this.cellSpace = cellSpace; }
    
    public String getTableAlign() { return tableAlign; }
    
    public void setTableAlign(String tableAlign) { this.tableAlign = tableAlign; }
    
    public String getName() { return name; }
    
    public void setName(java.lang.String name) { this.name = name; }
    
    public String getTableWidth() { return tableWidth; }
    
    public void setTableWidth(String tableWidth) { this.tableWidth = tableWidth; }
    
    public String getCellPad() { return cellPad; }
    
    public void setCellPad(String cellPad) { this.cellPad = cellPad; }
    
    public String getTableStyle() { return tableStyle; }
    
    public void setTableStyle(java.lang.String tableStyle) { this.tableStyle = tableStyle; }
    
    public String getInputStyle() { return inputStyle; }
    
    public void setInputStyle(String inputStyle) { this.inputStyle = inputStyle; }
    
    public String getCellStyle() { return cellStyle; }
    
    public void setCellStyle(String cellStyle) { this.cellStyle = cellStyle; }
    
    public String getCellWidth() { return cellWidth; }
    
    public void setCellWidth(String cellWidth) { this.cellWidth = cellWidth; }
    
    private int width;
    private int height;
    private String cellSpace;
    private String tableAlign;
    private String name;
    private String tableWidth;
    private String cellPad;
    private String tableStyle;
    private String inputStyle;
    private String cellStyle;
    private String cellWidth;
    
    public ControlCheckBox() {
        width = 3;
        cellSpace = "1";
        tableAlign = "center";
        name = "checkBox";
        tableWidth = "100%";
        cellPad = "1";
        tableStyle = "tableStyle";
        inputStyle = "inputStyle";
        cellStyle = "cellStyle";
        cellWidth = "33%";
    }
    
    public String draw(Vector vctValue, Vector vctCaption, Vector vctChecked) {
        if (vctCaption == null || vctCaption.size() <= 0) {
            System.out.println("Parameter error...");
            return null;
        }
        if (vctChecked == null) {
            System.out.println("Parameter error...");
            return null;
        }
        else {
            String str = new String("");
            str = "<table width=\"" + tableWidth + "\" cellSpacing=\"" + cellSpace + "\" cellPadding=\"" + cellPad +
            "\" class=\"" + tableStyle + "\" align=\"" + tableAlign + "\">\n";
            int count = 0;
            if(width>vctValue.size())
                width=vctValue.size();
            int countRow = vctValue.size() / width;
            if (vctValue.size() % width > 0)
                countRow = countRow + 1;
            for (int i = 0; i < countRow; i++) {
                str = str + "<tr>\n";
                for (int a = 0; a < width; a++) {
                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                    "\" nowrap><input type=\"checkbox\" name=\"" + name + "\" value=\"" + vctValue.get(count) +
                    "\" class=\"" + inputStyle + "\"";
                    for (int c = 0; c < vctChecked.size(); c++) {
                        if (vctValue.get(count).equals(vctChecked.get(c))) {
                            str = str + " checked";
                            break;
                        }
                    }
                    str = str + ">" + (String)vctCaption.get(count) + "</td>\n"; count++;
                    if (count >= vctValue.size())
                        break;
                }
                str = str + "</tr>\n";
            }
            str = str + "</table>";
            //            System.out.println(str);
            return str;
        }
    }
    
    
    public String draw(String name,Vector vctValue, Vector vctCaption, Vector vctChecked) {
        this.setName(name);
        if (vctCaption == null || vctCaption.size() <= 0) {
            System.out.println("Parameter error...");
            return null;
        }
        if (vctChecked == null) {
            System.out.println("Parameter error...");
            return null;
        }
        else {
            String str = new String("");
            str = "<table width=\"" + tableWidth + "\" cellSpacing=\"" + cellSpace + "\" cellPadding=\"" + cellPad +
            "\" class=\"" + tableStyle + "\" align=\"" + tableAlign + "\">";
            int count = 0;
            if(width>vctValue.size())
                width=vctValue.size();
            int countRow = vctValue.size() / width;
            if (vctValue.size() % width > 0)
                countRow = countRow + 1;
            for (int i = 0; i < countRow; i++) {
                str = str + "<tr>";
                for (int a = 0; a < width; a++) {
                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                    "\" nowrap><input type=\"checkbox\" name=\"" + name + "\" value=\"" + vctValue.get(count) +
                    "\" class=\"" + inputStyle + "\"";
                    for (int c = 0; c < vctChecked.size(); c++) {
                        if (vctValue.get(count).equals(vctChecked.get(c))) {
                            str = str + " checked";
                            break;
                        }
                    }
                    str = str + ">\n" + (String)vctCaption.get(count) + "</td>"; count++;
                    if (count >= vctValue.size())
                        break;
                }
                str = str + "</tr>";
            }
            str = str + "</table>";
            //            System.out.println(str);
            return str;
        }
    }
    
    
    public String draw(Vector vctName,Vector vctValue, Vector vctCaption, Vector vctChecked) {
        if (vctName == null || vctName.size() <= 0) {
            System.out.println("Parameter error...");
            return null;
        }
        if (vctCaption == null || vctCaption.size() <= 0) {
            System.out.println("Parameter error...");
            return null;
        }
        if (vctChecked == null) {
            System.out.println("Parameter error...");
            return null;
        }
        else {
            String str = new String("");
            str = "<table width=\"" + tableWidth + "\" cellSpacing=\"" + cellSpace + "\" cellPadding=\"" + cellPad +
            "\" class=\"" + tableStyle + "\" align=\"" + tableAlign + "\">";
            int count = 0;
            if(width>vctValue.size())
                width=vctValue.size();
            int countRow = vctValue.size() / width;
            if (vctValue.size() % width > 0)
                countRow = countRow + 1;
            for (int i = 0; i < countRow; i++) {
                str = str + "<tr>";
                for (int a = 0; a < width; a++) {
                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                    "\" nowrap><input type=\"checkbox\" name=\"" + (String)vctName.get(count) + "\" value=\"" + vctValue.get(count) +
                    "\" class=\"" + inputStyle + "\"";
                    for (int c = 0; c < vctChecked.size(); c++) {
                        String value = String.valueOf(vctValue.get(count));
                        String key = String.valueOf(vctChecked.get(c));
                        //System.out.println("key "+key + " = "+value);
                        if (value.equals(key)) {
                            str = str + " checked";
                            break;
                        }
                    }
                    str = str + ">" + (String)vctCaption.get(count) + "</td>"; count++;
                    if (count >= vctValue.size())
                        break;
                }
                str = str + "</tr>";
            }
            str = str + "</table>";
            return str;
        }
    }
    
    
    /**
     * gadnyana
     * for get values to check data values
     **/
    public Vector checkValuesCheckBox(Vector vCheck, String strKey){
        if(vCheck !=null && vCheck.size()>0){
            for(int j=0;j<vCheck.size();j++){
                Vector vChild = (Vector)vCheck.get(j);
                String str1 = (String)vChild.get(0);
                if(str1.equals(strKey)){
                    return vChild;
                }
            }
        }
        return new Vector(1,1);
    }
    
    
    public String drawMe(Vector vctValue, Vector vctValTextField, Vector vctCaption, Vector vctChecked) {
        if (vctValTextField == null || vctValTextField.size() <= 0) {
            System.out.println("Parameter error...");
            return null;
        }
        if (vctCaption == null || vctCaption.size() <= 0) {
            System.out.println("Parameter error...");
            return null;
        }
        if (vctChecked == null) {
            System.out.println("Parameter error...");
            return null;
        }
        else {
            String str = new String("");
            str = "<table width=\"" + tableWidth + "\" cellSpacing=\"" + cellSpace + "\" cellPadding=\"" + cellPad +
            "\" class=\"" + tableStyle + "\" align=\"" + tableAlign + "\">\n";
            int count = 0;
            int countRow = 0;
            if (vctValue.size() % width > 0)
                countRow = countRow + 1;
            for (int i = 0; i < countRow; i++) {
                if(vctValue.size() > 5){
                    str = str + "<tr>\n";
                    for (int a = 0; a < 5; a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap><input type=\"checkbox\" name=\"checkbox_"+a+"\" value=\"" + vctValue.get(count) +
                        "\" class=\"" + inputStyle + "\"";
                        for (int c = 0; c < vctChecked.size(); c++) {
                            String value = String.valueOf(vctValue.get(count));
                            String key = String.valueOf(vctChecked.get(c));
                            //System.out.println("key "+key + " = "+value);
                            if (value.equals(key)) {
                                str = str + " checked";
                                break;
                            }
                        }
                        str = str + ">&nbspPeriod : " + (String)vctCaption.get(count) + "</td>\n"; count++;
                        if (count >= vctValue.size())
                            break;
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    for (int a = 0; a < 5; a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "Budget</td>\n";
                        
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    for (int a = 0; a < 5; a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap><input type=\"text\" size=\"15\" name=\"budget_"+a+"\" value=\""+vctValTextField.get(a) +"\" class=\"" + inputStyle + "\"";
                        str = str + "></td>\n";
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    for (int a = 0; a < 5; a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "&nbsp</td>\n";
                        
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    for (int a = 5; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap><input type=\"checkbox\" name=\"checkbox_"+a+"\" value=\"" + vctValue.get(count) +
                        "\" class=\"" + inputStyle + "\"";
                        for (int c = 0; c < vctChecked.size(); c++) {
                            String value = String.valueOf(vctValue.get(count));
                            String key = String.valueOf(vctChecked.get(c));
                            //System.out.println("key "+key + " = "+value);
                            if (value.equals(key)) {
                                str = str + " checked";
                                break;
                            }
                        }
                        str = str + ">&nbspPeriod : " + (String)vctCaption.get(count) + "</td>\n"; count++;
                        if (count >= vctValue.size())
                            break;
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    for (int a = 5; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "Budget</td>\n";
                        
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    System.out.println("width ====> "+width);
                    for (int a = 5; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap><input type=\"text\" size=\"15\" name=\"budget_"+a+"\" value=\""+vctValTextField.get(a)+"\" class=\"" + inputStyle + "\"";
                        str = str + "></td>\n";
                    }
                    str = str + "</tr>\n";
                    
                }else{
                    
                    str = str + "<tr>\n";
                    for (int a = 0; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap><input type=\"checkbox\" name=\"checkbox_"+a+"\" value=\"" + vctValue.get(count) +
                        "\" class=\"" + inputStyle + "\"";
                        for (int c = 0; c < vctChecked.size(); c++) {
                            String value = String.valueOf(vctValue.get(count));
                            String key = String.valueOf(vctChecked.get(c));
                            //System.out.println("key "+key + " = "+value);
                            if (value.equals(key)) {
                                str = str + " checked";
                                break;
                            }
                        }
                        str = str + ">&nbspPeriod : " + (String)vctCaption.get(count) + "</td>\n"; count++;
                        if (count >= vctValue.size())
                            break;
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    for (int a = 0; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "Budget</td>\n";
                        
                    }
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    for (int a = 0; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap><input type=\"text\" size=\"15\" name=\"budget_"+a+"\" value=\""+vctValTextField.get(a)+"\" class=\"" + inputStyle + "\"";
                        str = str + "></td>\n";
                        
                    }
                    str = str + "</tr>\n";
                    
                }
            }
            
            str = str + "</table>";
            return str;
        }
    }
    
    /**
     * Created by dwi Jan 18, 2007
     * for AISO PNK created activity period link
     */
    
    public String drawME(Vector vctValue, Vector vctCaption, Vector vctChecked, String command, Vector vCheckPosted, String secondCom, String approot, long lActivityId) {
        ActivityPeriod objActivityPeriod = new ActivityPeriod();
        String strDisabled = "disabled";
        if (vctCaption == null || vctCaption.size() <= 0) {
            System.out.println("Parameter error...");
            return null;
        }
        if (vctChecked == null) {
            System.out.println("Parameter error...");
            return null;
        }
        else {
            String str = new String("");
            str = "<table width=\"" + tableWidth + "\" cellSpacing=\"" + cellSpace + "\" cellPadding=\"" + cellPad +
            "\" class=\"" + tableStyle + "\" align=\"" + tableAlign + "\">\n";
            int count = 0;
            int countRow = 0;
            
            if (vctValue.size() % width > 0)
                countRow = countRow + 1;
            int iPost = 0;
            for (int i = 0; i < countRow; i++) { 
                if(vctValue.size() > 5){
                    str = str + "<tr>\n";
                    
                    if(vCheckPosted != null && vCheckPosted.size() > 0){
                        for (int p = 0; p < 5; p++){                            
                            String strPosted = String.valueOf(vCheckPosted.get(p));
                            iPost = Integer.parseInt(strPosted);
                            for (int a = 0; a < 5; a++) {
                                if(iPost == PstActivityPeriod.PERIOD_CLOSED){
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"checkbox\" name=\"checkbox_"+p+"\" value=\"" + vctValue.get(p) +
                                    "\" class=\"" + inputStyle + "\" "+command+"\" checked disabled >&nbsp"+ (String)vctCaption.get(p) + "</td>\n";
                                }else{                                    
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"checkbox\" name=\"checkbox_"+p+"\" value=\"" + vctValue.get(p) +
                                    "\" class=\"" + inputStyle + "\" "+command+"";
                                    
                                    String value = String.valueOf(vctValue.get(p));
                                    Vector chk = checkValuesCheckBox(vctChecked,value);
                                    double dValText = 0.0;
                                    if(chk.size()>0){
                                        str = str + " checked";
                                        String valText = (String)chk.get(1);
                                        dValText = Double.parseDouble(valText);
                                    }
                                    if(dValText > 0){
                                        str = str + ">&nbsp<a href =\""+approot+"/masterdata/activity/act_dnc_link.jsp?oidActivityPeriod="+vctValue.get(p)+"&oidActivity="+lActivityId+"&dBudget="+dValText+"\">" + (String)vctCaption.get(p) + "</a></td>\n"; count++;
                                    }else{
                                        str = str + ">&nbsp" + (String)vctCaption.get(p) + "</td>\n"; count++;
                                    }
                                }
                                break;
                            }
                        }
                    } //akhir.......
                    
                    str = str + "</tr>\n";
                    
                    str = str + "<tr>\n";
                    for (int a = 0; a < 5; a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "Budget</td>\n";
                    }
                    
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    
                    if(vCheckPosted != null && vCheckPosted.size() > 0){
                        for (int p = 0; p < 5; p++){
                            String strPosted = String.valueOf(vCheckPosted.get(p));
                            iPost = Integer.parseInt(strPosted);
                            
                            for (int a = 0; a < 5; a++) {
                                
                                String value = String.valueOf(vctValue.get(p));
                                Vector chk = checkValuesCheckBox(vctChecked,value);
                                String valueText = "";
                                if(chk.size()>0){
                                    String valText = (String)chk.get(1);
                                    double dValText = Double.parseDouble(valText);
                                    valueText = Formater.formatNumber(dValText,"##,###.##");
                                }
                                
                                if(valueText != null && valueText.length() > 0)  
                                    strDisabled = "";
                                 else
                                    strDisabled = "disabled"; 
                                
                                if(iPost == PstActivityPeriod.PERIOD_CLOSED){
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"text\" disabled readonly=\"true\" size=\"15\" align=\"right\" name=\"budget_"+p+"\" value=\""+valueText+"\" class=\"" + inputStyle + "\"></td>\n";
                                }else{
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"text\" size=\"15\" "+strDisabled+" align=\"right\" name=\"budget_"+p+"\" value=\""+valueText+"\" "+secondCom+" class=\"" + inputStyle + "\"";
                                    str = str + "></td>\n";
                                }
                                break;
                            }
                        }
                    } //akhir.......
                    
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    
                    for (int a = 0; a < 5; a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "&nbsp</td>\n";
                    }
                    
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    
                    if(vCheckPosted != null && vCheckPosted.size() > 0){
                        for (int p = 5; p < vCheckPosted.size(); p++){                       
                                                      
                            String strPosted = String.valueOf(vCheckPosted.get(p));
                            iPost = Integer.parseInt(strPosted);
                            for (int a = 5; a < vctValue.size(); a++) {
                                if(iPost == PstActivityPeriod.PERIOD_CLOSED){
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap>"+ (String)vctCaption.get(p) + "</td>\n";
                                }else{
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"checkbox\" name=\"checkbox_"+p+"\" value=\"" + vctValue.get(p) +
                                    "\" class=\"" + inputStyle + "\" "+command+"";
                                    String value = String.valueOf(vctValue.get(p));
                                    Vector chk = checkValuesCheckBox(vctChecked,value);
                                    double dValText = 0.0;
                                    if(chk.size()>0){
                                        str = str + " checked ";
                                        String valText = (String)chk.get(1);
                                        dValText = Double.parseDouble(valText);
                                    }
                                    if(dValText > 0){
                                        str = str + ">&nbsp <a href =\""+approot+"/masterdata/activity/act_dnc_link.jsp?oidActivityPeriod="+vctValue.get(p)+"&oidActivity="+lActivityId+"&dBudget="+dValText+"\">" + (String)vctCaption.get(p) + "</a></td>\n"; count++;
                                    }else{
                                        str = str + ">&nbsp" + (String)vctCaption.get(p) + "</td>\n"; count++;
                                    }
                                }
                                break;
                            }
                        }
                    } //akhir.......
                    
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    
                    for (int a = 5; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "Budget</td>\n";
                        
                    }
                    
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    
                    if(vCheckPosted != null && vCheckPosted.size() > 0){
                        for (int p = 5; p < vCheckPosted.size(); p++){                           
                            
                            String strPosted = String.valueOf(vCheckPosted.get(p));
                            iPost = Integer.parseInt(strPosted);
                            for (int a = 5; a < vctValue.size(); a++) {
                                String value = String.valueOf(vctValue.get(p));
                                Vector chk = checkValuesCheckBox(vctChecked,value);
                                
                                
                                
                                String valueText = "";
                                if(chk.size()>0){
                                    String valText = (String)chk.get(1);
                                    double dValText = Double.parseDouble(valText);
                                    valueText = Formater.formatNumber(dValText,"##,###.##");
                                }
                                
                                if(valueText != null && valueText.length() > 0)  
                                    strDisabled = "";
                                 else
                                    strDisabled = "disabled"; 
                                
                                if(iPost == PstActivityPeriod.PERIOD_CLOSED){
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"text\" readonly=\"true\" size=\"15\" align=\"right\" name=\"budget_"+p+"\" value=\""+valueText+"\" class=\"" + inputStyle + "\"></td>\n";
                                }else{
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"text\" size=\"15\" "+strDisabled+" align=\"right\" name=\"budget_"+p+"\" value=\""+valueText+"\" "+secondCom+" class=\"" + inputStyle + "\"";
                                    str = str + "></td>\n";
                                }
                                break;
                            }
                        }
                    } //akhir.......
                    
                    str = str + "</tr>\n";
                    
                }else{
                    str = str + "<tr>\n";
                    
                    if(vCheckPosted != null && vCheckPosted.size() > 0){
                        for (int p = 0; p < vCheckPosted.size(); p++){
                            
                            System.out.println("vCheckPosted index ke : "+p);
                            
                            String strPosted = String.valueOf(vCheckPosted.get(p));
                            iPost = Integer.parseInt(strPosted);
                            
                            for (int a = 0; a < vctValue.size(); a++) {
                                if(iPost == PstActivityPeriod.PERIOD_CLOSED){
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap>"+ (String)vctCaption.get(p) + "</td>\n";
                                }else{
                                    System.out.println("vCheckPosted index ke : "+p);
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"checkbox\" name=\"checkbox_"+a+"\" value=\"" + vctValue.get(p) +
                                    "\" class=\"" + inputStyle + "\" "+command+"";
                                    String value = String.valueOf(vctValue.get(p));
                                    Vector chk = checkValuesCheckBox(vctChecked,value);
                                    double dValText = 0.0;
                                    String valText = "";
                                    if(chk.size()>0){
                                        str = str + " checked ";
                                        valText = (String)chk.get(1);
                                        dValText = Double.parseDouble(valText);
                                    }
                                    
                                    if(dValText > 0){
                                        str = str + ">&nbsp <a href =\""+approot+"/masterdata/activity/act_dnc_link.jsp?oidActivityPeriod="+vctValue.get(p)+"&oidActivity="+lActivityId+"&dBudget="+valText+"\">" + (String)vctCaption.get(p) + "</a></td>\n"; //count++;
                                    }else{
                                        str = str + ">&nbsp" + (String)vctCaption.get(p) + "</td>\n"; 
                                    }
                                }
                                break;
                            }
                        }
                    } //akhir.......
                    
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    
                    for (int a = 0; a < vctValue.size(); a++) {
                        str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                        "\" nowrap>";
                        str = str + "Budget</td>\n";
                        
                    }
                    
                    str = str + "</tr>\n";
                    str = str + "<tr>\n";
                    
                    if(vCheckPosted != null && vCheckPosted.size() > 0){
                        for (int p = 0; p < vCheckPosted.size(); p++){
                            String strPosted = String.valueOf(vCheckPosted.get(p));
                            iPost = Integer.parseInt(strPosted);
                            
                            for (int a = 0; a < vctValue.size(); a++) {
                                String value = String.valueOf(vctValue.get(p));
                                Vector chk = checkValuesCheckBox(vctChecked,value);
                                String valueText = "";
                                if(chk.size()>0){
                                    String valText = (String)chk.get(1);
                                    double dValText = Double.parseDouble(valText);
                                    valueText = Formater.formatNumber(dValText,"##,###.##");
                                }
                                
                                 if(valueText != null && valueText.length() > 0)  
                                    strDisabled = "";
                                 else
                                    strDisabled = "disabled"; 
                                
                                if(iPost == PstActivityPeriod.PERIOD_CLOSED){
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"text\" readonly=\"true\" size=\"15\" align=\"right\" name=\"budget_"+p+"\" value=\""+valueText+"\" class=\"" + inputStyle + "\"></td>\n";
                                }else{
                                    str = str + "<td width=\"" + cellWidth + "\" class=\"" + cellStyle +
                                    "\" nowrap><input type=\"text\" size=\"15\" "+strDisabled+" align=\"right\" name=\"budget_"+p+"\" value=\""+valueText+"\" "+secondCom+" class=\"" + inputStyle + "\"";
                                    str = str + "></td>\n";
                                }
                            }
                        }
                    } //akhir.......
                    
                    str = str + "</tr>\n";
                    
                }
            }
            
            str = str + "</table>";
            
            return str;
            
        }
    }
    
 String x = "Period: 2008";
 String y = x.substring(7,10);
 
    public Vector getCheckedBox(String values, String delim) {
        Vector vctChecked = new Vector();
        try{
            StringTokenizer st = new StringTokenizer(values, delim);
            while (st.hasMoreTokens())
                vctChecked.add(st.nextToken());
        }catch(Exception e){
            vctChecked.add("");
        }
        return vctChecked;
    }
    
    
    
    /*
    T E S T 123
     */
    /*public static void main(String[] arg) {
        ControlCheckBox c = new ControlCheckBox();
        c.setTableAlign("center");
        c.setTableWidth("80%");
        c.setWidth(8);
        Vector val = new Vector();
        Vector vPosted = new Vector();
        Vector valBudget = new Vector();
        String[] typeMaster =
        {"2007","2008","2009","2010", "2011","2012","2013","2014","2015","2016"};
        String[] strBudget =
        {"1.000.000","500.000","600.000","400.000","300.000","200.000","100.000","50.000","20.000","125.000"};
        String[] posted = {"1","0","2","2","2","2","2","2","2","2"};
        for(int p = 0; p < posted.length; p++ )
            vPosted.add(posted[p]);
        for (int i = 0; i < typeMaster.length; i++)
            val.add(typeMaster[i]);
        
        for (int j = 0; j < strBudget.length; j++)
            valBudget.add(strBudget[j]);
        
        System.out.println("vector val ===> " + val.size());
        System.out.println("vector valBudget ===> " + valBudget.size());
        Vector cap = val;
        Vector checked = new Vector();
        checked.add("Travelling");
        checked.add("Sport");
        //String x = c.drawME(val,cap,checked,"",vPosted);
        //System.out.println(x);
    }*/
    
    public static void main(String[] args){
         String x = "Period: 2008";
         String y = x.substring(7,12);
         System.out.println("Period: "+y);
    }
}
