<?xml version="1.0" encoding="UTF-8"?>
<web-app version="2.4" xmlns="http://java.sun.com/xml/ns/j2ee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">
    <display-name>Dimata Aiso</display-name>
    <servlet>
        <servlet-name>reportTabungan</servlet-name>
        <jsp-file>/report/simpanpinjam/tabungan.jsp</jsp-file>
    </servlet>
    <servlet>
        <servlet-name>ReportTabungan</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.report.ReportSimpanPinjam</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>ReportRangkumanTabungan</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.report.ReportSimpanPinjam</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>ReportKolektibiltas</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.report.ReportSimpanPinjam</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>ReportRangkumanKolektibiltas</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.report.ReportSimpanPinjam</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>BalanceSheetSummaryPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.neraca.BalanceSheetSummaryPdf</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>AjaxSetoran</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.transaksi.AjaxSetoran</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>AjaxPenarikan</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.transaksi.AjaxPenarikan</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>AjaxMutasi</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.transaksi.AjaxMutasi</servlet-class>
    </servlet>
    <servlet>
        <servlet-name>CountBunga</servlet-name>
        <servlet-class>com.dimata.sedana.ajax.transaksi.CountBunga</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>BalanceSheetSummaryPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.neraca.BalanceSheetSummaryPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>BalanceSheetPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.neraca.BalanceSheetPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>BalanceSheetPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.neraca.BalanceSheetPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>BalanceSheetXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.neraca.BalanceSheetXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>BalanceSheetXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.neraca.BalanceSheetXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>CashFlowDeptXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.aliranKas.CashFlowDeptXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>CashFlowDeptXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.aliranKas.CashFlowDeptXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>CashFlowDeptPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.aliranKas.CashFlowDeptPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>CashFlowDeptPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.aliranKas.CashFlowDeptPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>GeneralLedgerPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.bukuBesar.GeneralLedgerPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>GeneralLedgerPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.bukuBesar.GeneralLedgerPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>GeneralLedgerXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.bukuBesar.GeneralLedgerXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>GeneralLedgerXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.bukuBesar.GeneralLedgerXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>ProfitLossPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.ProfitLossPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>ProfitLossPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.ProfitLossPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>ProfitLossXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.ProfitLossXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>ProfitLossXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.ProfitLossXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLAnnualDetailPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLAnnualDetailPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLAnnualDetailPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLAnnualDetailPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLAnnualDetailXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLAnnualDetailXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLAnnualDetailXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLAnnualDetailXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLAnnualPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLAnnualPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLAnnualPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLAnnualPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLAnnualXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLAnnualXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLAnnualXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLAnnualXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLSummaryMTDYTDPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLSummaryMTDYTDPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLSummaryMTDYTDPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLSummaryMTDYTDPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLSummaryMTDYTDXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLSummaryMTDYTDXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLSummaryMTDYTDXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLSummaryMTDYTDXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLSummaryYTDWithVariancePdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLSummaryYTDWithVariancePdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLSummaryYTDWithVariancePdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLSummaryYTDWithVariancePdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLSummaryYTDWithVarianceXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLSummaryYTDWithVarianceXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLSummaryYTDWithVarianceXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLSummaryYTDWithVarianceXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>JournalListXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.jurnal.JournalListXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>JournalListXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.jurnal.JournalListXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLAnnualSummaryPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLAnnualSummaryPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLAnnualSummaryPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLAnnualSummaryPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>PLAnnualSummaryXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.labaRugi.PLAnnualSummaryXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>PLAnnualSummaryXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.labaRugi.PLAnnualSummaryXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>TrialBalanceDeptPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.neracaPercobaan.TrialBalanceDeptPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>TrialBalanceDeptPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.neracaPercobaan.TrialBalanceDeptPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>TrialBalanceDeptXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.neracaPercobaan.TrialBalanceDeptXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>TrialBalanceDeptXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.neracaPercobaan.TrialBalanceDeptXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>WorkSheetDeptPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.neracaLajur.WorkSheetDeptPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>WorkSheetDeptPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.neracaLajur.WorkSheetDeptPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>WorkSheetDeptXls</servlet-name>
        <servlet-class>com.dimata.sedana.report.neracaLajur.WorkSheetDeptXls</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>WorkSheetDeptXls</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.neracaLajur.WorkSheetDeptXls</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>ArApDetailReportPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.arap.ArApDetailReportPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>ArApDetailReportPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.arap.ArApDetailReportPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>ArApReportPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.arap.ArApReportPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>ArApReportPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.arap.ArApReportPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>AktivaPenyusutanPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.aktiva.AktivaPenyusutanPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>AktivaPenyusutanPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.aktiva.AktivaPenyusutanPdf</url-pattern>
    </servlet-mapping>
    <servlet>
        <servlet-name>JurnalPrintPdf</servlet-name>
        <servlet-class>com.dimata.sedana.report.jurnal.JurnalPrintPdf</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>JurnalPrintPdf</servlet-name>
        <url-pattern>/servlet/com.dimata.aiso.report.jurnal.JurnalPrintPdf</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ReportTabungan</servlet-name>
        <url-pattern>/report-tabungan.xls</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ReportRangkumanTabungan</servlet-name>
        <url-pattern>/report-rangkuman-tabungan.xls</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ReportKolektibiltas</servlet-name>
        <url-pattern>/report-kolektibilitas.xls</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>ReportRangkumanKolektibiltas</servlet-name>
        <url-pattern>/report-rangkuman-kolektibilitas.xls</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>AjaxSetoran</servlet-name>
        <url-pattern>/Setoran</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>AjaxPenarikan</servlet-name>
        <url-pattern>/Penarikan</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>AjaxMutasi</servlet-name>
        <url-pattern>/Mutasi</url-pattern>
    </servlet-mapping>
    <servlet-mapping>
        <servlet-name>CountBunga</servlet-name>
        <url-pattern>/count_bunga.jsp</url-pattern>
    </servlet-mapping>
    <session-config>
        <session-timeout>60</session-timeout>
    </session-config>
    <welcome-file-list>
        <welcome-file>index.jsp</welcome-file>
    </welcome-file-list>
</web-app>