/* Generated by Together */

package com.dimata.common.session.admin;

import com.dimata.common.form.admin.*;
import com.dimata.common.entity.admin.*;
import com.dimata.qdep.db.*;
import com.dimata.util.*;
import java.util.*;
import java.io.*;
import java.sql.*;                      


public class SessPrint {

    public static Vector getCountry(){
        DBResultSet dbrs = null;
        Vector result = new Vector(1,1);
        try{
            String sql = "SELECT A.CODE, A.AREA_NAME, A.CAPITAL_CITY, A.CONTINENT, V.VALUE AS CURRENCY FROM AREA AS A "+
				"INNER JOIN AREA_VALUES AS V ON A.AREA_OID = V.OWNER_OID "+
				"INNER JOIN AREA_PROPERTIES AS P ON P.PROPERTY_OID = V.PROPERTY_OID "+
				"WHERE P.PROPERTY_OID = 406 ";

            System.out.println("*********-----------"+sql);

            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            while(rs.next()){
                Vector vct = new Vector(1,1);
                vct.add(rs.getString("CODE"));
                vct.add(rs.getString("AREA_NAME"));
                vct.add(rs.getString("CAPITAL_CITY"));
                vct.add(rs.getString("CONTINENT"));
                vct.add(rs.getString("CURRENCY"));

                result.add(vct);

            }
        }
        catch(Exception e){
            System.out.println("Exception e : "+e.toString());
        }
        finally{
            DBResultSet.close(dbrs);
        }

        return result;

    }


     public static Vector getTelCharge(){
        DBResultSet dbrs = null;
        Vector result = new Vector(1,1);
        try{
            String sql = "select call_type_name, prefix_nr, telp_charge, unit_call_sec, area_name from telp_charge_hxs";

            System.out.println("*********-----------"+sql);

            dbrs = DBHandler.execQueryResult(sql);
            ResultSet rs = dbrs.getResultSet();
            while(rs.next()){
                Vector vct = new Vector(1,1);
                vct.add(rs.getString("call_type_name"));
                vct.add(rs.getString("prefix_nr"));
                vct.add(new Double(rs.getDouble("telp_charge")));
                vct.add(new Integer(rs.getInt("unit_call_sec")));
                vct.add(rs.getString("area_name"));

                result.add(vct);

            }
        }
        catch(Exception e){
            System.out.println("Exception e : "+e.toString());
        }
        finally{
            DBResultSet.close(dbrs);
        }

        return result;

    }

}
