/* Generated by Together */

package com.dimata.posbo.entity.search;

/* package java */
import java.util.*;
/* package qdep */
import com.dimata.qdep.entity.*;

public class SrcAccPayable {
    private String supplierName = "";
    private String invoiceNumber = "";
    private int invoiceDateStatus = 0;
    private Date startDate = new Date();
    private Date endDate = new Date();
    private long currencyId = 0;
    private int sortBy = 0;
    //for status summary rekap hutang
    private Vector apstatus = new Vector();
    
    public java.lang.String getSupplierName() {
        return supplierName;
    }
    
    public void setSupplierName(java.lang.String supplierName) {
        this.supplierName = supplierName;
    }
    
    public java.lang.String getInvoiceNumber() {
        return invoiceNumber;
    }
    
    public void setInvoiceNumber(java.lang.String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    
    public int getInvoiceDateStatus() {
        return invoiceDateStatus;
    }
    
    public void setInvoiceDateStatus(int invoiceDateStatus) {
        this.invoiceDateStatus = invoiceDateStatus;
    }
    
    public java.util.Date getStartDate() {
        return startDate;
    }
    
    public void setStartDate(java.util.Date startDate) {
        this.startDate = startDate;
    }
    
    public java.util.Date getEndDate() {
        return endDate;
    }
    
    public void setEndDate(java.util.Date endDate) {
        this.endDate = endDate;
    }
    
    public long getCurrencyId() {
        return currencyId;
    }
    
    public void setCurrencyId(long currencyId) {
        this.currencyId = currencyId;
    }
    
    public int getSortBy() {
        return sortBy;
    }
    
    public void setSortBy(int sortBy) {
        this.sortBy = sortBy;
    }

    /**
     * @return the apstatus
     */
    public Vector getApstatus() {
        return apstatus;
    }

    /**
     * @param apstatus the apstatus to set
     */
    public void setApstatus(Vector apstatus) {
        this.apstatus = apstatus;
    }
    
}
