/* Generated by Together */

package com.dimata.pos.entity.billing;

import com.dimata.qdep.entity.Entity;
import java.util.Hashtable;

public class Billdetail extends Entity {

    /**
     * @return the totalTax
     */
    public double getTotalTax() {
        return totalTax;
    }

    /**
     * @param totalTax the totalTax to set
     */
    public void setTotalTax(double totalTax) {
        this.totalTax = totalTax;
    }

    /**
     * @return the totalSvc
     */
    public double getTotalSvc() {
        return totalSvc;
    }

    /**
     * @param totalSvc the totalSvc to set
     */
    public void setTotalSvc(double totalSvc) {
        this.totalSvc = totalSvc;
    }
    private long billMainId = 0;
    private long unitId = 0;
    private long materialId = 0;
    private String itemName = "";
    private double itemPrice = 0.00;
    private int discType = 0;
    private double disc = 0.00;
    private double qty = 0;
    private double totalPrice = 0.00;
    private String sku = "";
    private int materialType = 0;
    private double cost = 0.00;
    private double discPct = 0.00;
    private Hashtable hashBilldetailCode = new Hashtable();
    private BillDetailCode billDetailCode = new BillDetailCode();
    private int updateStatus=0;
    private double amountAvailForReturn=0;
    private double qtyStock = 0;
    private double itemPriceStock = 0;
    private double discGlobal = 0;
    private double totalTax = 0;
    private double totalSvc = 0;
    
    public long getBillMainId() {
        return billMainId;
    }
    
    public void setBillMainId(long billMainId) {
        this.billMainId=billMainId;
    }
    
    public long getUnitId() {
        return unitId;
    }
    
    public void setUnitId(long unitId) {
        this.unitId=unitId;
    }
    
    public long getMaterialId() {
        return materialId;
    }
    
    public void setMaterialId(long materialId) {
        this.materialId=materialId;
    }
    
    public String getSku() {
        return sku;
    }
    
    public void setSku(String sku) {
        this.sku=sku;
    }
    
    public String getItemName() {
        return itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName=itemName;
    }
    
    public double getItemPrice() {
        return itemPrice;
    }
    
    public void setItemPrice(double itemPrice) {
        this.itemPrice=itemPrice;
    }
    
    public int getDiscType() {
        return discType;
    }
    
    public void setDiscType(int discType) {
        this.discType=discType;
    }
    
    public double getDisc() {
        return disc;
    }
    
    public void setDisc(double disc) {
        this.disc=disc;
    }
    
    public double getQty() {
        return qty;
    }
    
    public void setQty(double qty) {
        this.qty=qty;
    }
    
    public double getTotalPrice() {
        return totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice=totalPrice;
    }
    
    public int getMaterialType() {
        return materialType;
    }
    
    public void setMaterialType(int materialType) {
        this.materialType = materialType;
    }
    
    public double getCost() {
        return cost;
    }
    
    public void setCost(double cost) {
        this.cost=cost;
    }
    
    /**
     * Getter for property discPct.
     * @return Value of property discPct.
     */
    public double getDiscPct() {
        return discPct;
    }
    
    /**
     * Setter for property discPct.
     * @param discPct New value of property discPct.
     */
    public void setDiscPct(double discPct) {
        this.discPct = discPct;
    }
    
    /**
     * Getter for property billDetailCode.
     * @return Value of property billDetailCode.
     */
    public com.dimata.pos.entity.billing.BillDetailCode getBillDetailCode() {
        return billDetailCode;
    }
    
    /**
     * Setter for property billDetailCode.
     * @param billDetailCode New value of property billDetailCode.
     */
    public void setBillDetailCode(com.dimata.pos.entity.billing.BillDetailCode billDetailCode) {
        this.billDetailCode = billDetailCode;
    }
    
    /**
     * Getter for property hashBilldetailCode.
     * @return Value of property hashBilldetailCode.
     */
    public Hashtable getHashBilldetailCode() {
        return hashBilldetailCode;
    }
    
    /**
     * Setter for property hashBilldetailCode.
     * @param hashBilldetailCode New value of property hashBilldetailCode.
     */
    public void setHashBilldetailCode(Hashtable hashBilldetailCode) {
        this.hashBilldetailCode = hashBilldetailCode;
    }
    
    /**
     * Getter for property updateStatus.
     * @return Value of property updateStatus.
     */
    public int getUpdateStatus() {
        return updateStatus;
    }
    
    /**
     * Setter for property updateStatus.
     * @param updateStatus New value of property updateStatus.
     */
    public void setUpdateStatus(int updateStatus) {
        this.updateStatus = updateStatus;
    }
    
    /**
     * Getter for property amountAvailForReturn.
     * @return Value of property amountAvailForReturn.
     */
    public double getAmountAvailForReturn() {
        return amountAvailForReturn;
    }
    
    /**
     * Setter for property amountAvailForReturn.
     * @param amountAvailForReturn New value of property amountAvailForReturn.
     */
    public void setAmountAvailForReturn(double amountAvailForReturn) {
        this.amountAvailForReturn = amountAvailForReturn;
    }
    
    /**
     * Getter for property qtyStock.
     * @return Value of property qtyStock.
     */
    public double getQtyStock() {
        return qtyStock;
    }
    
    /**
     * Setter for property qtyStock.
     * @param qtyStock New value of property qtyStock.
     */
    public void setQtyStock(double qtyStock) {
        this.qtyStock = qtyStock;
    }
    
    public double getItemPriceStock() {
        return itemPriceStock;
    }
    
    public void setItemPriceStock(double itemPriceStock) {
        this.itemPriceStock = itemPriceStock;
    }
    
    /**
     * Getter for property discGlobal.
     * @return Value of property discGlobal.
     */
    public double getDiscGlobal() {
        return discGlobal;
    }
    
    /**
     * Setter for property discGlobal.
     * @param discGlobal New value of property discGlobal.
     */
    public void setDiscGlobal(double discGlobal) {
        this.discGlobal = discGlobal;
    }
    
}
