/* Generated by Together */

package com.dimata.pos.entity.payment;

import com.dimata.qdep.entity.Entity;
import java.util.Date;

public class CreditPaymentMain extends Entity {
    private long creditPaymentMainId;
    private long billMainId;
    private long cashCashierId;//
    private long locationId;//
    private long shiftId;//
    private long appUserId;//
    private Date billDate;
    private int billStatus = 0;
    private String salesCode = "";
    //private long specialId;
    //private int specialFlag=0;
    private String invoiceNumber;
    private int invoiceCounter;
    private int docType=0;
    
    
    public CreditPaymentMain(){}
    
    public long getCashCashierId(){
        return cashCashierId;}
    public void setCashCashierId(long cashCashierId){
        this.cashCashierId=cashCashierId;}
    
    public long getLocationId(){
        return locationId;}
    public void setLocationId(long locationId){
        this.locationId=locationId;}
    
    public long getShiftId(){
        return shiftId;}
    public void setShiftId(long shiftId){
        this.shiftId=shiftId;}
    
    public long getAppUserId(){
        return appUserId;}
    public void setAppUserId(long appUserId){
        this.appUserId=appUserId;}
    
    
    public Date getBillDate(){
        return billDate;}
    public void setBillDate(Date billDate){
        this.billDate=billDate;}
    
    
    public int getBillStatus() {
        return billStatus;
    }
    
    public void setBillStatus(int billStatus) {
        this.billStatus = billStatus;
    }
    
    public String getSalesCode() {
        return salesCode;
    }
    
    public void setSalesCode(String salesCode) {
        this.salesCode = salesCode;
    }
    
    /** Getter for property invoiceNumber.
     * @return Value of property invoiceNumber.
     *
     */
    public String getInvoiceNumber() {
        return this.invoiceNumber;
    }
    
    /** Setter for property invoiceNumber.
     * @param invoiceNumber New value of property invoiceNumber.
     *
     */
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
    
    public void setInvoiceCounter(int invoiceCounter) {
        this.invoiceCounter = invoiceCounter;
    }
    
    /** Getter for property invoiceCounter.
     * @return Value of property invoiceCounter.
     *
     */
    public int getInvoiceCounter() {
        return this.invoiceCounter;
    }
    
    /**
     * Getter for property creditPaymentMainId.
     * @return Value of property creditPaymentMainId.
     */
    public long getCreditPaymentMainId() {
        return creditPaymentMainId;
    }
    
    /**
     * Setter for property creditPaymentMainId.
     * @param creditPaymentMainId New value of property creditPaymentMainId.
     */
    public void setCreditPaymentMainId(long creditPaymentMainId) {
        this.creditPaymentMainId = creditPaymentMainId;
    }
    
    /**
     * Getter for property docType.
     * @return Value of property docType.
     */
    public int getDocType() {
        return docType;
    }
    
    /**
     * Setter for property docType.
     * @param docType New value of property docType.
     */
    public void setDocType(int docType) {
        this.docType = docType;
    }
    
    /**
     * Getter for property billMainId.
     * @return Value of property billMainId.
     */
    public long getBillMainId() {
        return billMainId;
    }
    
    /**
     * Setter for property billMainId.
     * @param billMainId New value of property billMainId.
     */
    public void setBillMainId(long billMainId) {
        this.billMainId = billMainId;
    }
    
    /**
     * Getter for property specialId.
     * @return Value of property specialId.
     */
    //public long getSpecialId ()
    //{
    //    return specialId;
    //}
    
    /**
     * Setter for property specialId.
     * @param specialId New value of property specialId.
     */
    //public void setSpecialId (long specialId)
    //{
    //   this.specialId = specialId;
    //}
    
    /**
     * Getter for property specialFlag.
     * @return Value of property specialFlag.
     */
    //public int getSpecialFlag ()
    //{
    
    //  return specialFlag;
    //}
    
    /**
     * Setter for property specialFlag.
     * @param specialFlag New value of property specialFlag.
     */
    //public void setSpecialFlag (int specialFlag)
    //{
    //    this.specialFlag = specialFlag;
    //}
    
    /**
     * Getter for property parentId.
     * @return Value of property parentId.
     */
    //public long getParentId ()
    //{
    //    return parentId;
    //}
    
    /**
     * Setter for property parentId.
     * @param parentId New value of property parentId.
     */
    //public void setParentId (long parentId)
    //{
    //    this.parentId = parentId;
    //}
    
}
